name: ThermoProjects
channels:
  - defaults
dependencies:
  - jupyter
  - markdown
  - markdown-it-py
  - markupsafe
  - matplotlib
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - numpy
  - pandas
  - pandoc
  - pandocfilters
  - python>=3.7
  - scipy
